### ISSUE TITLE
Does not start

### ISSUE THREAD

**Issue by SirGordon** [TheYellowThorn/sandcastle#1]
Could not find another place to report that SandCastle.exe does not work. I have purchased it, installed on my windows 8.0 and when it starts the only thing i can see is a black window.

**Comment by TheYellowThorn** [comment]
The file that downloads should be an .air file and not an .exe. The program should prompt the user to install Adobe Air if it is not installed on the computer. The file should automatically install with the Adobe Air Application Installer. Please let me know if these steps do not work for you.

Thank you.

Sent from Yahoo Mail on Android

**Comment by SirGordon** [comment]
Sure i have downloaded .air first, installed it and tried to run. I have one of the latest AIR version on my desktop because I am an AIR programmer.

**Comment by TheYellowThorn** [comment]
If you dont mind, can you create a ticket at: 
http://theyellowthorn.com/reporting

Please include a screenshot so the team can better investigate the issue. Thank you.

Sent from Yahoo Mail on Android

**Comment by SirGordon** [comment]
Unfortunately, captcha on that page does not display, so I can't report a bug.

**Comment by SirGordon** [comment]
Registered on word press so captcha was not required. Created a ticket with a screenshot attached.

**Comment by TheYellowThorn** [comment]
Thank you. We will take a look and get you a response as soon as possible. We apologize for the inconvenience.

Sent from Yahoo Mail on Android

**Comment by SirGordon** [comment]
That black screen would'nt tell much.. Does SandCastle log anything?

**Comment by TheYellowThorn** [comment]
If you open the program with ADL, it will tell you if an error is being thrown.

Sent from Yahoo Mail on Android

**Comment by SirGordon** [comment]
TypeError: Error #1009: Cannot access a property or method of a null object reference.
    at com.terrainbuilder.interfacebuild.menu::NativeMenuSystem()
    at AIRPlayground/initMenuSystem()
    at AIRPlayground/onContextCreate()
    at flash.events::EventDispatcher/dispatchEventFunction()
    at flash.events::EventDispatcher/dispatchEvent()
    at away3d.core.managers::Stage3DProxy/onContext3DUpdate()

**Comment by TheYellowThorn** [comment]
Very helpful! We will get back to you with a fix as soon as we can. Again, sorry for the inconvenience. Thanks again.

Sent from Yahoo Mail on Android

**Comment by SirGordon** [comment]
By the way, can you please tell me, if I install, run and enter license key on one of my computers, would I be able to run it on another one later? Or does it bind to the first one?

**Comment by TheYellowThorn** [comment]
There is a limit to the amount of computers you can use the key on, but you should be able to install with the same key on another computer.

Sent from Yahoo Mail on Android

**Comment by TheYellowThorn** [comment]
The application file has been updated on FastSpring. Since you ordered the application today, your FastSpring download link should still be active and will download the most recent file. Thanks for your patience. Let us know if you can now get into the program.

Sent from Yahoo Mail on Android

**Comment by SirGordon** [comment]
Thank you very much! It works now.
