### ISSUE TITLE
Code from this repo cannot be compiled because of obvious errors

### ISSUE THREAD

**Issue by SirGordon** [TheYellowThorn/sandcastle#2]
141 _subGeometry = _seamlessElevationData.geometry.subGeometries[0];
ISubGeometry is not assignable to SubGeometry

1386 return new cross1;
did you mean "cross1" (without "new")?

Did you test it before pushing to github?

**Comment by SirGordon** [comment]
there are lots of code style problems in multiple files as well..

**Comment by TheYellowThorn** [comment]
cross1 should be without "new"  We will update the source code.  Which compiler are you using?  line 141 does not throw an error.  Are you using the most recent release version of Away3D?

**Comment by TheYellowThorn** [comment]
What kind of styling problems are you occurring?  Is it conflicting with the formatting in your compiler?

**Comment by SirGordon** [comment]
Oh, my bad, I'm using dev version of Away3D because there are some bug fixes.

**Comment by SirGordon** [comment]
No, it's just not-formatted. For example: https://github.com/Radiosatch2000/sandcastle/blob/release/com/terrainbuilder/objs/terrain/SeamlessElevation.as

**Comment by TheYellowThorn** [comment]
That's GitHub.  The formatting doesn't look like that on our local machines.  I'll dig deeper to see if GitHub is reformatting on upload for some reason.  Thanks for the feedback.

**Comment by SirGordon** [comment]
No, it does not reformat. It's because both spaces and tabs are used. Restrict to use either only spaces or only tabs.
