### ISSUE TITLE
Multiple LightPicker NPE in API

### ISSUE THREAD

**Issue by SirGordon** [TheYellowThorn/sandcastle#3]
Export a project from SandCastle without light, or use existing, but do not set lightPicker anywhere. Leave it to be null. Catch multiple null pointer exceptions. AIR is mostly for mobile, where real-time lighting and shadowing slows FPS too much, so it never get used on mobile, so SandCastle should work without light and imo this is a critical issue.

**Comment by TheYellowThorn** [comment]
The terrain materials for SandCastle require at lease one directional light.

**Comment by SirGordon** [comment]
Then it cannot be used on mobile phones

**Comment by TheYellowThorn** [comment]
Most mobile phones can handle at least one directional light.  Which phone were you testing on?

**Comment by SirGordon** [comment]
Sure they can, if there is only terrain and some static objects.
In 3D game, we have some skeleton-animated characters running around on top of the terrain, some particle effects made with Sparticle, a forest of trees, feathers and Away3D GUI elements.
I think, with all this, GPU load is too high even for a tablet to handle real-time lighting.

**Comment by TheYellowThorn** [comment]
That is always a tricky task with mobile development and AIR, balancing the needs of the application with the power of the device.

Some tips to get better mobile performance with SandCastle:
- Use the ColorTerrainMaterial - it requires fewer texture calls in AGAL
- Use a LightPicker on just the terrain material
- Be frugal with the amount of terrain splats you add.  While there are technically unlimited splats that can be added, you are still limited by the power of the GPU and system memory.
- Adjust the level of detail settings.  Use lower LODs for mobile Apps - you should also only need higher detail up close
  - Use 256x256 or 512x512 TerrainBlocks to keep texture sizes down
- Adjust the far clipping plane to lower poly count

**Comment by SirGordon** [comment]
Thanks for the tips!
But I think there still should be a no-light mode.

**Comment by TheYellowThorn** [comment]
Go ahead and add it as feature request at http://www.theyellowthorn.com/reporting.  We value our users' input, and we will make every effort to include it in our next release.

**Comment by TheYellowThorn** [comment]
One other important tip:  If you're worried about performance, set "useNormalMaps" to false on your ColorTerrainMaterials and TerrainMaterials.
